title: Coffee & Papers
name: "Oliver's Learning Blog"
author: Oliver JÃ¤rnefelt
twitter_username: jarnefeltoliver
baseurl: "/coffeepapers"
description: Document my learning notes.
profile_url: "http://jarnefeltoliver.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
